# : Manager {{{

[mgr]
cwd = { fg = "#BFBDB6" }

# Hovered
hovered = { bg = "#152537", bold = true }
preview_hovered = { bg = "#152537" }

# Find
find_keyword = { fg = "#95E6CB", bold = true, italic = true, underline = true }
find_position = { fg = "#95E6CB", bold = true, italic = true }

# Marker
marker_copied = { fg = "#59C2FF", bg = "#59C2FF" }
marker_cut = { fg = "#F26D78", bg = "#F26D78" }
marker_marked = { fg = "#95E6CB", bg = "#95E6CB" }
marker_selected = { fg = "#FF8F40", bg = "#FF8F40" }

# Count
count_copied = { fg = "#0B0E14", bg = "#59C2FF" }
count_cut = { fg = "#BFBDB6", bg = "#F26D78" }
count_selected = { fg = "#0B0E14", bg = "#FF8F40" }

# Border
border_symbol = "│"
border_style = { fg = "#1B2733" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#0F131A", bg = "#FFCC66", bold = true }
inactive = { fg = "#BFBDB6", bg = "#0F131A" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#0F131A", bg = "#FFB454", bold = true }
normal_alt = { fg = "#FFB454", bg = "#0F131A" }

# Select mode
select_main = { fg = "#0F131A", bg = "#95E6CB", bold = true }
select_alt = { fg = "#95E6CB", bg = "#0F131A" }

# Unset mode
unset_main = { fg = "#0F131A", bg = "#F26D78", bold = true }
unset_alt = { fg = "#F26D78", bg = "#0F131A" }

# : }}}

# : Indicator of hovered file {{{

[indicator]
parent  = { bg = '#152537' }
current = { bg = '#152537' }
preview = { bg = '#152537' }
# Change padding to full square
padding = { open = "█", close = "█" }

# : }}}


# : Status {{{

[status]
sep_left = { open = "", close = "┃" }
sep_right = { open = "┃", close = "" }
overall = { bg = "#0F131A" }

# Permissions
perm_type = { fg = "#BFBDB6" }
perm_read = { fg = "#39BAE6" }
perm_write = { fg = "#F26D78" }
perm_exec = { fg = "#95E6CB" }
perm_sep = { fg = "#70809b" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#FFCC66" }
progress_error = { fg = "#F26D78" }

# : }}}


# : Which {{{

[which]
cols = 3
mask = { bg = "#0B0E14" }
cand = { fg = "#FFCC66" }
rest = { fg = "#70809b" }
desc = { fg = "#BFBDB6" }
separator = " ▶ "
separator_style = { fg = "#0B0E14" }

# : }}}


# : Confirm {{{

[confirm]
border = { fg = "#FFCC66" }
title = { fg = "#BFBDB6", bold = true }
content = { fg = "#BFBDB6" }
list = { fg = "#BFBDB6" }
btn_yes = { fg = "#0B0E14", bg = "#95E6CB", bold = true }
btn_no = { fg = "#0B0E14", bg = "#F26D78", bold = true }
btn_labels = ["Yes", "No"]

# : }}}


# : Spot {{{

[spot]
border = { fg = "#FFCC66" }
title = { fg = "#BFBDB6", bold = true }
tbl_col = { fg = "#FF8F40", bold = true }
tbl_cell = { fg = "#BFBDB6" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#FFCC66" }
active = { fg = "#FF8F40", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#FFCC66" }
title = { fg = "#BFBDB6", bold = true }
value = { fg = "#BFBDB6" }
selected = { bg = "#152537" }

# : }}}


# : Cmp {{{

[cmp]
border = { fg = "#FFCC66", bg = "#0B0E14" }
active = { fg = "#FF8F40", bold = true }
inactive = {}
icon_file = ""
icon_folder = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#FFCC66" }
title = {}
hovered = { fg = "#39BAE6", underline = true }

# : }}}


# : Help {{{

[help]
on = { fg = "#FFCC66" }
run = { fg = "#59C2FF" }
desc = { fg = "#BFBDB6" }
hovered = { fg = "#FF8F40", bold = true }
footer = { fg = "#0B0E14", bg = "#BFBDB6" }
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#59C2FF" }
title_warn = { fg = "#FFB454" }
title_error = { fg = "#F26D78" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#FFB454" },

  # Media
  { mime = "{audio,video}/*", fg = "#D2A6FF" },

  # Archives
  { mime = "application/{,g}zip", fg = "#F26D78" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#F26D78" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#59C2FF" },


  # Special files
  { name = "*", is = "orphan", bg = "#1B2733" },
  { name = "*", is = "exec", fg = "#95E6CB" },

  # Dummy files
  { name = "*", is = "dummy", bg = "#1B2733" },
  { name = "*/", is = "dummy", bg = "#1B2733" },

  # Fallback
  { name = "*/", fg = "#70809b" },
]
